In [2]:
%matplotlib notebook
%pylab

Using matplotlib backend: nbAgg
Populating the interactive namespace from numpy and matplotlib


In [25]:
#  form a 3by3 matrix
qin = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(qin)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# swap q_in[m,i,j] with q_in[i,j,m]
for m in range(3):
    for i in range(3):
        for j in range(3):
            qin[m,:,:] = qin[i,:,:]
qin

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed